version: '3'
services:
  other_other_wireguard:
    build: .
    cap_add:
      - net_admin
      - sys_module
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    ports:
      - 51820:51820
