version: '2'
services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - 5672:5672
    hostname: 'rabbitmq'
    environment:
      RABBITMQ_ERLANG_COOKIE: 'gsOM3sl8GIcNtz'
      RABBITMQ_DEFAULT_USER: 'test'
      RABBITMQ_DEFAULT_PASS: 'qMBqoIE69a24vRutmXGgvolOMgfAst9a7ntaewC0I'
      RABBITMQ_DEFAULT_VHOST: '/'
    labels:
      NAME: 'rabbitmq'
