apiVersion: v1
kind: Pod
metadata:
  name: wireguard-pod
spec:
  containers:
    - name: wireguard
      image: gcr.io/vpn-traffic-analysis/github.com/lukebaal/vpntrafficanalysis:latest
      volumeMounts:
        - mountPath: /logs
          name: logs-volume
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
  volumes:
    - name: logs-volume
      emptyDir: {}
