apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wireguard
  labels:
    name: wireguard-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
