apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wireguard
  labels:
    name: wireguard-pod
  namespace: dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          # image: gcr.io/vpn-traffic-analysis/github.com/lukebaal/vpntrafficanalysis:latest
          image: wireguard
          volumeMounts:
            - mountPath: /logs
              name: logs-volume
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: 51820
              protocol: UDP
      volumes:
        - name: logs-volume
          emptyDir: {}
