version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "node_server/package.json" }}
            - v1-dependencies-
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "frontend/package.json" }}
            - v1-dependencies-
      - run:
          name: Install backend dependencies
          command: npm --prefix node_server install && npm --prefix frontend install
      # - tests:
      #     name: Run Backend/Frontend tests
      #     command: npm --prefix node_backend install
      - save_cache:
          paths:
            - node_server/node_modules
          key: v1-dependencies-{{ checksum "node_server/package.json" }}
      - save_cache:
          paths:
            - frontend/node_modules
          key: v1-dependencies-{{ checksum "frontend/package.json" }}
      - deploy:
          name: Deploy
          command: |
            ssh $DROPLET_USER@$DROPLET_HOST "./run_deploy.sh"
